service: service-warranty-reminder
configValidationMode: error

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  logRetentionInDays: 30

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameters
          Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${sls:stage}/${self:service}/*'

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  services-reminder:
    handler: handler.servicesReminder
    name: ${sls:stage}--${self:service}
    environment:
      SSM_PATH: /${sls:stage}/${self:service}
      SERVICE_NAME: ${self:service}
      LOG_LEVEL: INFO
    events:
      - schedule: rate(10 minutes)
