service: service-warranty-reminder
configValidationMode: error

plugins:
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-2
  logRetentionInDays: 30

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameters
          Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${sls:stage}/${self:service}/*'

package:
  patterns:
    - '!creds/**'
    - '!.env'
    - '!__tests__'
    - '!__fixtures__'
    - '!__mocks__'
    - '!coverage'

functions:
  services-reminder:
    handler: handler.servicesReminder
    name: ${sls:stage}--${self:service}
    environment:
      SSM_PATH: /${sls:stage}/${self:service}
      SERVICE_NAME: ${self:service}
      LOG_LEVEL: INFO
      NODE_OPTIONS: --enable-source-maps
    events:
      - schedule: cron(0 10 * * ? *)

custom:
  prune:
    automatic: true
    number: 3
